name: CI

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Compile ldid
        run: |
          sudo apt update
          sudo apt install -y libplist-dev libssl-dev pkg-config
          git clone git://git.saurik.com/ldid.git
          cd ldid
          g++ -pipe -o ldid ldid.cpp -I. -x c lookup2.c -lcrypto -lplist -Os -fwhole-program -flto -s -L/usr/lib/x86_64-linux-gnu
          cd ..
          echo "${{github.workspace}}/ldid" >> $GITHUB_PATH
      - run: bun install
      - run: bun run build
      - run: python tests/test.py
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: bin/*.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/*.zip
          tag: ${{ github.ref }}
          file_glob: true
